blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name='landing_page'),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostDetailView, AddPostReviewView, EditReviewView, ConfirmDeleteReviewView, \
    DeleteReviewView, AddPostView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:id>/', PostDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddPostReviewView.as_view(), name='reviews'),
    path("<int:post_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name='edit_review'),
    path("<int:post_id>/reviews/<int:review_id>/delete/confirm", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:post_id>/reviews/<int:review_id>/delete", DeleteReviewView.as_view(), name='delete-review'),
    path("create/", AddPostView.as_view(), name='create')

]

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'posts:post_list' as post_list %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-edit' as profile_edite_page_url %}
{% url 'posts:create' as create %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Blog{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body  class="mx-5">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--        <li class="nav-item">-->
<!--          <a class="nav-link {%if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>-->
<!--        </li>-->
        <li class="nav-item">
          <a class="nav-link {%if request.path == post_list %} active {% endif %}" aria-current="page" href="{{ post_list }}">Posts</a>
        </li>
      </ul>
        <div  class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {%if request.path == profile_page_url or request.path == profile_edite_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                    <li><a class="dropdown-item" href="{{ create }}">Post qo'shish</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                  </ul>
                </li>
                </ul>

            {% else %}
                <a class="btn btn-outline-info" href="{% url 'users:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
  </div>
</nav>
<div class="container">
    {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                  {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/landing_page.html
{% extends 'base.html' %}
{% block content %}
  <h3>Eng Yangi Postlar</h3>
    {% if posts %}
        {% for post in posts %}
                <div class="row mb-4">
                    <div class="col-2 me-4">
                        <img src="{{ post.image.url }}" class="cover-pic">
                    </div>
                    <div class="col-6 ms-4">
                        <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
                        <p>Tags:
                            {% for tag in post.tags.all %}
                              {{ tag.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </p>
                            <p>Status: {{ post.status }}</p>
                        <p>
                            {{ post.created_at }}
                        </p>
                    </div>
                </div>
        {% endfor %}
    {% else %}
          No posts found.
    {% endif %}

{% endblock %}