blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name='landing_page'),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostDetailView, AddPostReviewView, EditReviewView, ConfirmDeleteReviewView, \
    DeleteReviewView, AddPostView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:id>/', PostDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddPostReviewView.as_view(), name='reviews'),
    path("<int:post_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name='edit_review'),
    path("<int:post_id>/reviews/<int:review_id>/delete/confirm", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:post_id>/reviews/<int:review_id>/delete", DeleteReviewView.as_view(), name='delete-review'),
    path("create/", AddPostView.as_view(), name='create')

]

posts/models.py
from django.utils import timezone
from django.db import models
from taggit.managers import TaggableManager
from users.models import CustomUser

class   Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('published', 'Published'),
    ]
    title = models.CharField(max_length=250)
    content = models.TextField()
    image = models.ImageField(default='defaukt_post_image.png')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='user_posts')
    tags = TaggableManager()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='draft')

    def __str__(self):
        return self.title

class PostVisit(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='visit_logs')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Visit on {self.timestamp} for post {self.post.title}'

class Reviews(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='izohlar')
    review_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Review by {self.user.username} on {self.post.title}'

posts/forms.py
from django import forms
from posts.models import Reviews, Category
from .models import Post
class PostReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('review_text',)

class AddPostForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Kategoriyani tanlang")
    class Meta:
        model = Post
        fields = ('title', 'content', 'image', 'category', 'tags')

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views import View
from posts.forms import PostReviewForm, AddPostForm
from posts.models import Post, Reviews

class HomeView(View):
    def get(self, request):
        latest_posts = Post.objects.filter(status='published').order_by('-created_at')[:5]

        context = {
            'posts': latest_posts,
        }
        return render(request, 'landing_page.html', context)

class AddPostView(View):
    def get(self, request):
        post_form = AddPostForm()
        context = {
            'post_form': post_form,
        }
        return render(request, 'posts/add_post.html', context)

    def post(self, request):
        post_form = AddPostForm(request.POST, request.FILES)

        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.status = 'Draft'
            post.save()
            return redirect('posts:post_list')

        return render(request, 'posts/add_post.html', {'post_form': post_form})  # Xatolik bo‘lsa, formani qaytarish

class PostListView(View):
    def get(self, request):
        posts = Post.objects.filter(status='published').order_by('-created_at')
        return render(request, 'posts/post_list.html', {'posts': posts})

class PostDetailView(View):
    def get(self, request, id):
        post = Post.objects.get(id=id)
        review_form = PostReviewForm()
        reviews = post.izohlar.all().order_by('-created_at')
        context = {
            'post': post,
            'review_form': review_form,
            'reviews': reviews,
        }
        return render(request, 'posts/post_detail.html', context)

class AddPostReviewView(View):
    def post(self, request, id):
        post = Post.objects.get(id=id)
        reviews = post.izohlar.all().order_by('-created_at')
        review_form = PostReviewForm(data=request.POST)
        if review_form.is_valid():
            Reviews.objects.create(
                post=post,
                user=request.user,
                review_text=review_form.cleaned_data['review_text'],
            )
            return redirect(reverse("posts:detail", kwargs={'id': post.id}))
        context = {
            'post': post,
            'review_form': review_form,
            'reviews': reviews,
        }
        return render(request, 'posts/post_detail.html', context)

class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        revirew = post.izohlar.get(id=review_id)
        review_form =PostReviewForm(instance=revirew)
        context = {
                    'post': post,
                    'review': revirew,
                    'review_form': review_form,
                    }
        return render(request, 'posts/edit_review.html', context)

    def post(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        revirew = post.izohlar.get(id=review_id)
        review_form = PostReviewForm(instance=revirew, data=request.POST)
        if review_form.is_valid():
            revirew.review_text = review_form.cleaned_data['review_text']
            revirew.save()
            return redirect(reverse("posts:detail", kwargs={'id': post.id}))
        context = {
            'post': post,
            'review': revirew,
            'review_form': review_form,
        }
        return render(request, 'posts/edit_review.html', context)

class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        revirew = post.izohlar.get(id=review_id)
        context = {
            'post': post,
            'review': revirew,
        }
        return render(request, 'posts/confirm_delete.html', context)

class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        revirew = post.izohlar.get(id=review_id)
        revirew.delete()
        messages.success(request, "You have successfully deleted this review")
        return redirect(reverse("posts:detail", kwargs={'id': post.id}))

posts/templates/posts/add_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h3>Post Create Page</h3>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    {{ post_form|crispy }}
                </div>

                <button class="btn btn-success">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Confirm Review{% endblock %}
{% block content %}
<h3>Are you sure you want  to delete this review?</h3>
<p>
  <b>Post:</b> {{ post.title }}
</p>
<p>
  <b>Comment:</b> {{ review.review_text }}
</p>
<a href="{% url 'posts:delete-review' post.id review.id %}" class="btn btn-outline-danger">Yes</a>
<a class="btn btn-outline-primary" href="{% url 'posts:detail' post.id %}">No</a>
{% endblock %}

posts/templates/posts/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit Review{% endblock %}
{% block content %}
<h3>Edit Review</h3>
<div class="row mb-4">
    <div class="col-6">
        <form method="post" action="{% url 'posts:edit_review' post.id review.id %}">
            {% csrf_token %}
            <div class="mb-3">
                {{ review_form.review_text|as_crispy_field }}
            </div>

            <button class="btn btn-success">Save</button>
        </form>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load hitcount_tags %}

{%block content%}
  <div class="row">
        <div class="col-2 me-4">
            <img class="cover-pic" src="{{ post.image.url }}" alt="cover picture">
        </div>
        <div class="col-6 ms-4">
          <h2>{{ post.category.name }}</h2>
            <h3>{{ post.title }}</h3>
            <span class="fst-italic">
            Authored by {{ post.author }}
            </span>
            <p>Ko‘rilganlar soni: {{ hitcount.hits }}</p>
            <div class="col-1 me-2">
                {% if post.author.profile_pic %}
                    <img class="small-profile-pic" src="{{ post.author.profile_pic.url }}" alt="Muallif rasmi">
                {% else %}
                    <img class="small-profile-pic" src="default_profile_pic.png" alt="Default muallif rasmi">
                {% endif %}
            </div>
            <div class="col-2">
                <p>Tags:
                {% for tag in post.tags.all %}
                  {{ tag.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
                <p>Status: {{ post.status }}</p>
            </div>
            <div class="col-6">
            {% if request.user.is_authenticated %}
                <form method="post" action="{% url 'posts:reviews' post.id %}">
                    {% csrf_token %}
                    {{ review_form.review_text|as_crispy_field  }}
                    <button class="btn btn-success">Add Review</button>
                </form>
            {% endif %}
        </div>
        </div>
    </div>
    {% if post.izohlar.exists %}
        <h3>Review</h3><hr>
        {% for review in reviews %}
            <div class="row mb-3">
                <div class="col-1 me-2">
                    <img class="small-profile-pic" src="{{ review.user.profile_pic.url}}" alt="profile_pic">
                </div>
                <div class="col-7">
                    <b>{{ review.user.username }}</b> <span class="fw-lighter">{{ review.created_at }}</span>
                    {% if review.user == request.user %}
                        <a href="{% url 'posts:edit_review' post.id review.id %}"><i class="bi bi-pen"></i></a>
                        <a href="{% url 'posts:confirm-delete-review' post.id review.id %}"><i class="bi bi-trash"></i></a>
                    {% endif %}
                    <p class="font-monospace">{{ review.review_text }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{%endblock%}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{%block content%}
    <h3>Post List Page</h3>
    {% if posts %}
        {% for post in posts %}
                <div class="row mb-4">
                    <div class="col-2 me-4">
                        <img src="{{ post.image.url }}" class="cover-pic">
                    </div>
                    <div class="col-6 ms-4">
                        <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
                        <p>Tags:
                            {% for tag in post.tags.all %}
                              {{ tag.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </p>
                            <p>Status: {{ post.status }}</p>
                        <p>
                            {{ post.created_at }}
                        </p>
                    </div>
                </div>
        {% endfor %}
    {% else %}
          No posts found.
    {% endif %}
{%endblock%}